name = "mcp_toolkit_gleam"
version = "1.0.0"

description = "Production-ready Model Context Protocol (MCP) Toolkit - comprehensive server implementation in Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "mikkihugo", repo = "mcp-gleam" }

# Core dependencies (required for all functionality)
[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_json = ">= 2.3.0 and < 3.0.0"
jsonrpc = ">= 1.0.0 and < 2.0.0"
justin = ">= 1.0.1 and < 2.0.0"
gleam_erlang = ">= 0.34.0 and < 1.0.0"

# Transport configuration
# Set transport_mode to control which dependencies are included:
# - "stdio": stdio transport only (no external dependencies)  
# - "full": all transports including WebSocket/SSE (requires mist)
[config]
transport_mode = "full"

# Conditional dependencies based on transport_mode
[dependencies.mist]
version = ">= 3.0.0 and < 4.0.0"
optional = true

# Build targets
[[binaries]]
name = "mcpstdio"
path = "./src/mcpstdio.gleam"
description = "MCP server with stdio transport only (dependency-free)"

[[binaries]]
name = "mcpserver"  
path = "./src/mcpserver.gleam"
description = "MCP server with all transports (requires mist when transport_mode=full)"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
simplifile = ">= 2.2.1 and < 3.0.0"
birdie = ">= 1.2.7 and < 2.0.0"
